server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://34.47.225.165"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true

      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: auth-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: item-service-route
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/items/**

        - id: claim-service-route
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/api/claims/**

eureka:
  client:
    service-url:
      defaultZone: http://34.47.225.165:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    ip-address: 34.47.225.165

